# Generated by Django 3.0.5 on 2020-08-25 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_date', models.DateField()),
                ('check_out_time', models.TimeField()),
                ('date_booked', models.DateField()),
                ('is_cancelled', models.BooleanField()),
                ('cancelled_date', models.DateField(null=True)),
                ('total_days', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('no_of_rooms', models.IntegerField(default=1)),
                ('payment_ref', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.IntegerField()),
                ('services', models.IntegerField()),
                ('suggestions', models.CharField(max_length=200, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboarding.RoomBooking')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('rooms_available', models.IntegerField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Rooms')),
            ],
        ),
    ]
