# Generated by Django 3.0.5 on 2020-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarding', '0002_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='no_of_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
