# Generated by Django 3.0.5 on 2020-08-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarding', '0003_roombooking_no_of_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='reason_cancelled',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='cancelled_date',
            field=models.DateField(null=True),
        ),
    ]
