# Generated by Django 3.0.5 on 2020-08-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarding', '0004_auto_20200824_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.IntegerField()),
                ('services', models.IntegerField()),
                ('suggestions', models.CharField(max_length=200, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboarding.RoomBooking')),
            ],
        ),
    ]
