# Generated by Django 3.0.5 on 2020-08-22 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200822_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='room_pics/'),
            preserve_default=False,
        ),
    ]
