# Generated by Django 3.0.5 on 2020-08-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rooms_room_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
