# Generated by Django 3.0.5 on 2020-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_delete_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_desc', models.CharField(max_length=200)),
                ('room_occ', models.IntegerField()),
                ('room_price', models.IntegerField()),
                ('no_of_rooms_avail', models.IntegerField()),
                ('room_class', models.CharField(choices=[('Economy', 'Economy'), ('Premium', 'Premium')], max_length=10)),
                ('room_img', models.ImageField(upload_to='room_pics/')),
            ],
        ),
    ]
